name: Asset
description: Add an icon or illustration
title: "[asset] "
labels: ["chore", "triage"]
projects: "andij/1"
body:
  - type: markdown
    attributes:
      value: |
        Naming convention for the title is: `[asset]` type (`icon` or `illustration`) name (e.g. 'pencil')
        Example: `[asset] icon pencil`

  - type: textarea
    id: proposal
    attributes:
      label: Description
      description: |
        Include a link to the comment in the Proposal where the asset was proposed.

  - type: checkboxes
    id: design
    attributes:
      label: Design and community
      options:
        - label: This asset is unique and has a clear purpose
        - label: Completed user recognition testing
        - label: Community is in agreement with this addition
        - label: Confirm this asset aligns with Brand expectations
        - label: Asset aligns to the grid in the Figma UI Kit
        - label: Acceptable quality of vector. (Minimal anchor points, no masks, no strokes, 2px minimum width, combined and flattened.)
        - label: Create a Figma branch for the asset in the UI Kit
        - label: Submit this Figma branch for review

  - type: textarea
    id: name
    attributes:
      label: Suggest any additional names
      description: This → ✏️ is a pencil, not an edit
      placeholder: e.g. 'pencil'

  - type: checkboxes
    id: integration
    attributes:
      label: Integration
      options:
        - label: Export the SVG from Figma to exacting standards
        - label: Create a feature branch
        - label: Include SVG code in `brands/british-gas/icons [or] illustrations/index.js`
        - label: Regenerate the test snapshots
        - label: Raise a pull request
        - label: Seek approval
