name: Asset
description: Add an icon or illustration
title: "[asset] "
labels: ["chore", "triage"]
projects: "andij/1"
body:
  - type: markdown
    attributes:
      value: |
        Naming convention for the title is: `[asset]` type (`icon` or `illustration`) name (e.g. 'pencil')
        Example: `[asset] icon pencil`

  - type: textarea
    id: proposal
    attributes:
      label: Description
      description: |
        Include a link to the comment in the Proposal where the asset was proposed.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: This asset is unique and has a clear purpose
        - label: Completed user recognition testing
        - label: Community is in agreement with this addition
        - label: Confirm this asset aligns with Brand expectations
        - label: Asset aligns to the grid in the Figma UI Kit
        - label: Acceptable quality of vector. (Minimal anchor points, no masks, no strokes, 2px minimum width, combined and flattened.)
        - label: Create a Figma branch for the asset in the UI Kit
        - label: Submit this Figma branch for review

  - type: textarea
    id: name
    attributes:
      label: Suggest any alternative names
      description: This → ✏️ is a pencil, not an edit.
      placeholder: e.g. 'pencil', 'pen', 'crayon'

  - type: checkboxes
    id: integration
    attributes:
      label: Integration
      options:
        - label: Export the SVG from Figma to exacting standards
        - label: Create a feature branch in `centrica-engineering/nucleus-util` 
        - label: Include SVG paths in `brands/british-gas/icons` [or] `illustrations/index.js`
        - label: Regenerate test snapshots
        - label: Raise a pull request
        - label: Seek approval

  - type: checkboxes
    id: deployment
    attributes:
      label: Deployment
      options:
        - label: Test 
        - label: Release and update version. Refer to the [Release process](https://github.com/centrica-engineering/nucleus-internal-handbook/blob/main/release/release-process.md#nucleus-util)
