name: Move to Prioritised

on:
  project_card:
    types: [moved]

jobs:
  update_issue:
    if: github.event.project_card.column_id == '8e96a9fa'
    runs-on: ubuntu-latest

    steps:
    - name: Extract issue number
      id: extract_issue_number
      run: echo "::set-output name=ISSUE_NUMBER::$(echo ${GITHUB_EVENT_PROJECT_CARD_CONTENT_URL##*/})"

    - name: Remove 'triage' label
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: triage
        issue_number: ${{ steps.extract_issue_number.outputs.ISSUE_NUMBER }}

    - name: Add 'available' label
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: available
        issue_number: ${{ steps.extract_issue_number.outputs.ISSUE_NUMBER }}
